apiVersion: v1
kind: Pod
metadata:
  name: nvidia-smi
  namespace: folding
spec:
  tolerations:
    - key: "node.k8s.dfds.cloud/gpu"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"
    - key: "nvidia.com/gpu"
      operator: "Exists"
      effect: "NoSchedule"
  restartPolicy: OnFailure
  containers:
    - name: nvidia-smi
      image: nvidia/cuda:9.2-devel
      args:
        - "nvidia-smi"
      resources:
        limits:
          nvidia.com/gpu: 1
