apiVersion: v1
kind: Service
metadata:
  name: fahclient-0
  namespace: folding
  labels:
    app: fahclient
spec:
  selector:
    statefulset.kubernetes.io/pod-name: fahclient-0
  type: LoadBalancer
  loadBalancerIP: 192.168.0.17
  ports:
    - name: web
      port: 7396
      protocol: TCP
      targetPort: 7396
    - name: command
      port: 36330
      protocol: TCP
      targetPort: 36330

---
apiVersion: v1
kind: Service
metadata:
  name: fahclient-1
  namespace: folding
  labels:
    app: fahclient
spec:
  selector:
    statefulset.kubernetes.io/pod-name: fahclient-1
  type: LoadBalancer
  loadBalancerIP: 192.168.0.18
  ports:
    - name: web
      port: 7396
      protocol: TCP
      targetPort: 7396
    - name: command
      port: 36330
      protocol: TCP
      targetPort: 36330

---
apiVersion: v1
kind: Service
metadata:
  name: fahclient-2
  namespace: folding
  labels:
    app: fahclient
spec:
  selector:
    statefulset.kubernetes.io/pod-name: fahclient-2
  type: LoadBalancer
  loadBalancerIP: 192.168.0.19
  ports:
    - name: web
      port: 7396
      protocol: TCP
      targetPort: 7396
    - name: command
      port: 36330
      protocol: TCP
      targetPort: 36330
