apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: fahclient
  name: fahclient
  namespace: folding
spec:
  serviceName: "fahclient"
  replicas: 3
  selector:
    matchLabels:
      app: fahclient
  volumeClaimTemplates:
    - metadata:
        name: fahclient-vol
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
  template:
    metadata:
      labels:
        app: fahclient
    spec:
      priorityClassName: low-priority
      tolerations:
        - key: "node.k8s.dfds.cloud/gpu"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
        - key: "nvidia.com/gpu"
          operator: "Exists"
          effect: "NoSchedule"
      nodeSelector:
        node.k8s.dfds.cloud/gpu: "true"
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                      - fahclient
              topologyKey: "kubernetes.io/hostname"
      volumes:
        - name: fahclient-secret
          secret:
            secretName: fahclient
      containers:
        - name: fahclient
          image: abstrask/folding:nvidia-opencl-latest
          env:
            - name: power
              value: full
            - name: command-enable
              value: "true"
          command:
            - /usr/bin/FAHClient
          args:
            - -v
            - --data-directory=/etc/fahclient
            - --power=$(power)
            - --gpu=true
            - --fold-anon=false
            - --gui-enabled=false
            - --allow=0/0
            - --web-enable=false
            - --command-enable=$(command-enable)
            - --command-allow-no-pass=127.0.0.1
            - --run-as=nobody
          ports:
            - name: web
              containerPort: 7396
            - name: command
              containerPort: 36330
          resources:
            limits:
              nvidia.com/gpu: 1
          securityContext:
            allowPrivilegeEscalation: false
            capabilities: {}
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: true
            runAsUser: 65534
          volumeMounts:
            - name: fahclient-vol
              mountPath: /etc/fahclient
          workingDir: /etc/fahclient
      initContainers:
        - name: init-fah
          image: debian:buster-slim
          command:
            - /bin/sh
          args:
            - -c
            - cp /etc/fahclient-config.xml /etc/fahclient/config.xml && chown -R 65534:65534 /etc/fahclient
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: false
            runAsUser: 0
          volumeMounts:
            - name: fahclient-vol
              mountPath: /etc/fahclient
            - name: fahclient-secret
              subPath: "config.xml"
              mountPath: "/etc/fahclient-config.xml"
