apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: fahclient
  name: fahclient
  namespace: folding
spec:
  selector:
    app: fahclient
  type: LoadBalancer
  ports:
    - name: web
      port: 7396
      protocol: TCP
      targetPort: 7396
    - name: command
      port: 36330
      protocol: TCP
      targetPort: 36330
