apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: fahclient
  name: fahclient
  namespace: folding
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fahclient
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: fahclient
    spec:
      priorityClassName: low-priority
      tolerations:
        - key: "node.k8s.dfds.cloud/gpu"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
      nodeSelector:
        node.k8s.dfds.cloud/gpu: "true"
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                      - fahclient
              topologyKey: "kubernetes.io/hostname"
      # volumes:
      #   - emptyDir: {}
      #     name: shared
      volumes:
        - name: fahclient-vol
          persistentVolumeClaim:
            claimName: fahclient-pvc
      containers:
        - name: fahclient
          image: debian:buster-slim
          env:
            - name: gpu
              value: "true"
            - name: power
              # value: full
              value: light
            - name: web-enable
              value: "true"
            - name: command-enable
              value: "true"
          command:
            - /shared/usr/bin/FAHClient
          args:
            - -v
            - --gpu=$(gpu)
            - --power=$(power)
            # - --cpus=8
            - --fold-anon=true
            - --gui-enabled=false
            # - --allow=127.0.0.1 10.1.1.1
            - --allow=0/0
            - --web-enable=$(web-enable)
            # - --web-allow=0/0:7396
            - --web-allow=0/0
            # - --web-allow=10.1.1.1/32
            - --command-enable=$(command-enable)
            # - --command-allow-no-pass=10.1.1.1/32
            - --command-allow-no-pass=0/0
            - --run-as=nobody
          ports:
            - name: web
              containerPort: 7396
            - name: command
              containerPort: 36330
          securityContext:
            allowPrivilegeEscalation: false
            capabilities: {}
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: true
            runAsUser: 65534
          volumeMounts:
            - mountPath: /shared
              name: fahclient-vol
          workingDir: /shared/usr/bin/
      initContainers:
        - name: install-fah
          image: debian:buster-slim
          args:
            - -c
            - apt update && apt install -y wget && wget https://download.foldingathome.org/releases/public/release/fahclient/debian-stable-64bit/v${major_version}/fahclient_${minor_version}_amd64.deb && dpkg -x fahclient_${minor_version}_amd64.deb /shared/ && touch /shared/usr/bin/log.txt && chown -R 65534:65534 /shared
          command:
            - /bin/sh
          env:
            - name: major_version
              value: "7.5"
            - name: minor_version
              value: "7.5.1"
          # resources:
          #   limits:
          #     cpu: "1"
          #     memory: 256Mi
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: false
            runAsUser: 0
          volumeMounts:
            - mountPath: /shared
              name: fahclient-vol
